const elementText=`2|He|ヘリウム;3|Li|リチウム;4|Be|ベリリウム;10|Ne|ネオン;11|Na|ナトリウム;12|Mg|マグネシウム;13|Al|アルミニウム;14|Si|ケイ素;17|Cl|塩素;18|Ar|アルゴン;20|Ca|カルシウム;21|Sc|スカンジウム;22|Ti|チタン;24|Cr|クロム;25|Mn|マンガン;26|Fe|鉄;27|Co|コバルト;28|Ni|ニッケル;29|Cu|銅;30|Zn|亜鉛;31|Ga|ガリウム;32|Ge|ゲルマニウム;33|As|ヒ素;34|Se|セレン;35|Br|臭素;36|Kr|クリプトン;37|Rb|ルビジウム;38|Sr|ストロンチウム;40|Zr|ジルコニウム;41|Nb|ニオブ;42|Mo|モリブデン;43|Tc|テクネチウム;44|Ru|ルテニウム;45|Rh|ロジウム;46|Pd|パラジウム;47|Ag|銀;48|Cd|カドミウム;49|In|インジウム;50|Sn|スズ;51|Sb|アンチモン;52|Te|テルル;54|Xe|キセノン;55|Cs|セシウム;56|Ba|バリウム;57|La|ランタン;58|Ce|セリウム;59|Pr|プラセオジム;60|Nd|ネオジム;61|Pm|プロメチウム;62|Sm|サマリウム;63|Eu|ユウロピウム;64|Gd|ガドリニウム;65|Tb|テルビウム;66|Dy|ジスプロシウム;67|Ho|ホルミウム;68|Er|エルビウム;69|Tm|ツリウム;70|Yb|イッテルビウム;71|Lu|ルテチウム;72|Hf|ハフニウム;73|Ta|タンタル;75|Re|レニウム;76|Os|オスミウム;77|Ir|イリジウム;78|Pt|白金（プラチナ）;79|Au|金;80|Hg|水銀;81|Tl|タリウム;82|Pb|鉛;83|Bi|ビスマス;84|Po|ポロニウム;85|At|アスタチン;86|Rn|ラドン;87|Fr|フランシウム;88|Ra|ラジウム;89|Ac|アクチニウム;90|Th|トリウム;91|Pa|プロトアクチニウム;93|Np|ネプツニウム;94|Pu|プルトニウム;95|Am|アメリシウム;96|Cm|キュリウム;97|Bk|バークリウム;98|Cf|カリホルニウム;99|Es|アインスタイニウム;100|Fm|フェルミウム;101|Md|メンデレビウム;102|No|ノーベリウム;103|Lr|ローレンシウム;104|Rf|ラザホージウム;105|Db|ドブニウム;106|Sg|シーボーギウム;107|Bh|ボーリウム;108|Hs|ハッシウム;109|Mt|マイトネリウム;110|Ds|ダームスタチウム;111|Rg|レントゲニウム;112|Cn|コペルニシウム;113|Nh|ニホニウム;114|Fl|フレロビウム;115|Mc|モスコビウム;116|Lv|リバモリウム;117|Ts|テネシン;118|Og|オガネソン`;
const gases=new Set(['He','Ne','Cl','Ar','Kr','Xe','Rn','Og']), liquids=new Set(['Br','Hg']), metalloids=new Set(['Si','Ge','As','Sb','Te','At']), nonmetals=new Set(['He','Ne','Cl','Ar','Se','Br','Kr','Xe','Rn','Ts','Og']);
const uses={He:'風船や気球を浮かせる軽い気体',Li:'スマートフォンなどの充電池',Ne:'ネオンサイン',Na:'食塩を構成する元素のひとつ',Mg:'軽量合金や花火',Al:'缶やアルミホイル',Si:'半導体やガラス',Cl:'水道水やプールの消毒',Ar:'電球や溶接の保護ガス',Ca:'骨や歯の主要成分',Ti:'眼鏡や医療用インプラント',Cr:'ステンレス鋼やメッキ',Mn:'乾電池や鉄鋼',Fe:'建物、工具、血液中のヘモグロビン',Co:'青い顔料や充電池',Ni:'硬貨やステンレス鋼',Cu:'電線や10円玉',Zn:'さび止めメッキや乾電池',Br:'難燃剤や写真材料',Ag:'宝飾品、電子部品、抗菌用品',Sn:'はんだや缶のコーティング',Xe:'車のライトや麻酔',Pt:'宝飾品や排ガス浄化触媒',Au:'宝飾品や電子部品',Hg:'温度計など（現在は使用を削減）',Pb:'自動車用バッテリーや放射線遮蔽',Nd:'非常に強力な永久磁石',Ba:'胃のX線検査の造影剤',Am:'煙感知器',Nh:'日本で命名された人工元素'};
function period(n){return n<=2?1:n<=10?2:n<=18?3:n<=36?4:n<=54?5:n<=86?6:7;}
const elements=elementText.split(';').map(row=>{const [n,symbol,name]=row.split('|'),number=Number(n);return{number,symbol,name,period:period(number),state:gases.has(symbol)?'気体':liquids.has(symbol)?'液体':'固体',type:metalloids.has(symbol)?'半金属':nonmetals.has(symbol)?'非金属':'金属',use:uses[symbol]|| (number>=93?'人工的に作られ、主に基礎科学で研究される元素':'特殊材料や科学研究に利用される元素')};});
const bySymbol=Object.fromEntries(elements.map(e=>[e.symbol.toUpperCase(),e]));
const easySymbols=new Set(['He','Li','Ne','Na','Mg','Al','Si','Cl','Ar','Ca','Ti','Cr','Mn','Fe','Co','Ni','Cu','Zn','Br','Ag','Sn','Xe','Pt','Au']);
const usedLetters=new Set(elements.flatMap(e=>[...e.symbol.toUpperCase()])), rows=['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'];
let answer,guesses,current,finished,hintLevel;
const board=document.querySelector('#board'),keyboard=document.querySelector('#keyboard'),message=document.querySelector('#message');
function pool(){return document.querySelector('#modeSelect').value==='easy'?elements.filter(e=>easySymbols.has(e.symbol)):elements;}
function updateAttempt(n){const bar=document.querySelector('#attemptBar'),progress=bar.parentElement,colors=['bg-success','bg-info','bg-warning','bg-danger'];bar.style.width=`${n*25}%`;bar.classList.remove(...colors);bar.classList.add(colors[n-1]);document.querySelector('#attemptStatus').textContent=`ATTEMPT ${n} / 4`;progress.setAttribute('aria-valuenow',n);}
function startGame(){const choices=pool();answer=choices[Math.floor(Math.random()*choices.length)];guesses=[];current='';finished=false;hintLevel=0;board.innerHTML=Array.from({length:4},(_,r)=>`<div class="board-row">${[0,1].map(c=>`<div class="tile" id="tile-${r}-${c}"></div>`).join('')}</div>`).join('');keyboard.innerHTML=rows.map((letters,i)=>`<div class="key-row">${i===2?'<button class="key wide" data-key="ENTER">決定</button>':''}${[...letters].map(k=>`<button class="key" data-key="${k}" ${usedLetters.has(k)?'':'disabled'}>${k}</button>`).join('')}${i===2?'<button class="key wide" data-key="BACKSPACE">⌫</button>':''}</div>`).join('');document.querySelector('#propertyLog').innerHTML='';document.querySelector('#hintPanel').classList.add('d-none');document.querySelector('#hintPanel').innerHTML='';document.querySelector('#hintCount').textContent='0/3';document.querySelector('#hintButton').disabled=false;updateAttempt(1);message.textContent='';renderChoices();renderCurrent();}
function renderChoices(){document.querySelector('#elementChoices').innerHTML=pool().map(e=>`<button class="element-choice" data-symbol="${e.symbol.toUpperCase()}" data-bs-dismiss="modal"><strong>${e.symbol}</strong><small>${e.name}</small></button>`).join('');}
function renderCurrent(){if(finished)return;for(let c=0;c<2;c++){const t=document.querySelector(`#tile-${guesses.length}-${c}`);t.textContent=current[c]||'';t.classList.toggle('filled',Boolean(current[c]));}}
function tell(text){message.textContent=text;clearTimeout(tell.timer);tell.timer=setTimeout(()=>message.textContent='',1800);}
function score(guess){const result=['absent','absent'],remain={},target=answer.symbol.toUpperCase();for(let i=0;i<2;i++){if(guess[i]===target[i])result[i]='correct';else remain[target[i]]=(remain[target[i]]||0)+1;}for(let i=0;i<2;i++)if(result[i]!=='correct'&&remain[guess[i]]){result[i]='present';remain[guess[i]]--;}return result;}
function submit(){if(current.length<2)return tell('2文字入力してください');const guessed=bySymbol[current];if(!guessed)return tell('実在する2文字元素記号を入力してください');const r=guesses.length,result=score(current),submitted=current;guesses.push(submitted);current='';result.forEach((state,c)=>setTimeout(()=>document.querySelector(`#tile-${r}-${c}`).classList.add('reveal',state),c*220));updateKeys(submitted,result);addProperty(guessed,r+1);if(submitted===answer.symbol.toUpperCase())setTimeout(()=>finish(true),600);else if(guesses.length===4)setTimeout(()=>finish(false),600);else{updateAttempt(guesses.length+1);renderCurrent();}}
function addProperty(e,n){document.querySelector('#propertyLog').insertAdjacentHTML('beforeend',`<div class="property-item"><b>${n}. ${e.symbol} ${e.name}</b><span class="property-tags"><span>${e.type}</span><span>${e.state}</span><span>第${e.period}周期</span></span></div>`);}
function revealHint(){if(finished||hintLevel>=3)return;hintLevel++;const hints=[`分類：<span class="hint-chip">${answer.type}</span>　常温：<span class="hint-chip">${answer.state}</span>`,`周期表：<span class="hint-chip">第${answer.period}周期</span>`,`身近な用途：${answer.use}`];document.querySelector('#hintPanel').classList.remove('d-none');document.querySelector('#hintPanel').insertAdjacentHTML('beforeend',`<div>ヒント${hintLevel}：${hints[hintLevel-1]}</div>`);document.querySelector('#hintCount').textContent=`${hintLevel}/3`;if(hintLevel===3)document.querySelector('#hintButton').disabled=true;}
function updateKeys(guess,result){const rank={absent:1,present:2,correct:3};[...guess].forEach((letter,i)=>{const key=document.querySelector(`[data-key="${letter}"]`),old=['absent','present','correct'].find(s=>key.classList.contains(s));if(!old||rank[result[i]]>rank[old]){key.classList.remove('absent','present','correct');key.classList.add(result[i]);}});}
function finish(won){finished=true;const modal=document.querySelector('#resultModal');modal.classList.remove('result-win','result-loss');modal.classList.add(won?'result-win':'result-loss');document.querySelector('#resultTitle').innerHTML=won?'<i class="fa-solid fa-circle-check me-2"></i>正解！':'<i class="fa-solid fa-vial-circle-xmark me-2"></i>惜しい！';document.querySelector('#resultIconGlyph').className=`fa-solid ${won?'fa-trophy':'fa-flask-vial'}`;document.querySelector('#resultKicker').textContent=won?'BRILLIANT DISCOVERY':'NEXT EXPERIMENT';document.querySelector('#resultText').textContent=won?`${guesses.length}回で ${answer.symbol}（${answer.name}）を発見しました。`:`正解は ${answer.symbol}（${answer.name}）でした。`;document.querySelector('#elementCard').innerHTML=`<div class="element-card-head"><div class="atomic-tile"><small>${answer.number}</small>${answer.symbol}</div><div><h3 class="h5 mb-1">${answer.name}</h3><div class="text-secondary">${answer.type}・${answer.state}・第${answer.period}周期</div></div></div><hr><b><i class="fa-solid fa-book-open me-2"></i>主な用途・豆知識</b><p class="mb-0 mt-1">${answer.use}</p>`;bootstrap.Modal.getOrCreateInstance(modal).show();}
function input(key){if(finished)return;if(key==='ENTER')return submit();if(key==='BACKSPACE'){current=current.slice(0,-1);return renderCurrent();}if(/^[A-Z]$/.test(key)&&usedLetters.has(key)&&current.length<2){current+=key;renderCurrent();}}
function setTheme(choice){const effective=choice==='auto'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):choice;document.documentElement.dataset.theme=effective;document.documentElement.dataset.themeChoice=choice;document.querySelectorAll('.theme-option').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===choice));document.querySelector('#themeMenuIcon').className=`fa-solid ${choice==='light'?'fa-sun':choice==='dark'?'fa-moon':'fa-circle-half-stroke'}`;document.querySelectorAll('.modal').forEach(m=>m.dataset.bsTheme=effective);try{localStorage.setItem('elementle-theme',choice)}catch(e){}}
function setMode(mode){const input=document.querySelector('#modeSelect');if(input.value===mode)return;input.value=mode;document.querySelectorAll('.mode-option').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));startGame();}
keyboard.addEventListener('click',e=>{const key=e.target.closest('[data-key]');if(key&&!key.disabled)input(key.dataset.key);});document.querySelector('#elementChoices').addEventListener('click',e=>{const choice=e.target.closest('[data-symbol]');if(choice){current=choice.dataset.symbol;renderCurrent();}});document.addEventListener('keydown',e=>{const key=e.key.toUpperCase();if(key==='ENTER'||key==='BACKSPACE'||/^[A-Z]$/.test(key)){e.preventDefault();input(key);}});document.querySelector('#hintButton').addEventListener('click',revealHint);document.querySelector('#resultModal').addEventListener('hidden.bs.modal',()=>{if(finished)startGame();});document.querySelector('#brandButton').addEventListener('click',e=>{e.preventDefault();startGame();});document.querySelectorAll('.mode-option').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.querySelectorAll('.theme-option').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.themeChoice)));matchMedia('(prefers-color-scheme: light)').addEventListener('change',()=>{if(document.documentElement.dataset.themeChoice==='auto')setTheme('auto')});setTheme(document.documentElement.dataset.theme||'dark');startGame();
